global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'load-generator'
    metrics_path: /metrics
    static_configs:
      - targets: ['load-generator:8000']
